name: Deploy SQL

on:
  push:
    branches:
      - main
    paths:
      - "database/**/*.sql"

jobs:
  deploy-sql:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check MySQL connection
        run: |
          mysql \
            -h 127.0.0.1 \
            -u jeeva \
            -p"${{ secrets.DB_PASSWORD }}" \
            config_mysql \
            -e "SELECT 'MySQL connection successful' AS message;"

      - name: Deploy SQL files
        run: |
          find database -name "*.sql" -type f -print0 | while IFS= read -r -d '' file
          do
            echo "Deploying: $file"

            mysql \
              -h 127.0.0.1 \
              -u jeeva \
              -p"${{ secrets.DB_PASSWORD }}" \
              config_mysql < "$file"

            echo "Successfully deployed: $file"
          done